// {name:"aom" ,
//     email: "aom@mail.com" ,
//     tel: "0645788451"
//   }

export interface Student{
  name: string;
  email: string;
  tel: string;
  createDate ?: Date;    //?ำให้มีก็ได้ไม่มีก็ได้
}

// Generated by https://quicktype.io

export interface ResponseStudentAll {
  result: StudentModel[];
}

export interface StudentModel {
  createBy:   null;
  createDate: Date | null;
  email:      string;
  id:         number;
  name:       string;
  tel:        null | string;
  updateBy:   null;
  updateDate: Date | null;
  version:    number;
}

export interface StudentAllCondition {
  name?: string,
  email?: string,
  tel?: string}

